apiVersion: apps/v1
kind: Deployment
metadata:
  name: app41
  labels:
    app: app41
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app41
  template:
    metadata:
      labels:
        app: app41
    spec:
      containers:
      - name: app41
        image: "docker.io/caceresabelanibal/app41:latest"
        ports:
        - containerPort: 80